"""Crypto — AES, ECDH, KDF, Vault integration (Fase 2)."""

from app.crypto.aes import (
    AES_KEY_SIZE,
    AES_NONCE_SIZE,
    EncryptedData,
    decrypt,
    decrypt_key,
    decrypt_raw,
    decrypt_string,
    derive_key_from_bytes,
    encrypt,
    encrypt_key,
    encrypt_string,
    generate_file_key,
    generate_nonce,
)
from app.crypto.rsa import (
    RSAKeyPair,
    decrypt_private_key,
    encrypt_private_key,
    encrypt_with_public_key,
    decrypt_with_private_key,
    generate_keypair,
    sign_data,
    verify_signature,
)
from app.crypto.ecdh import (
    generate_x25519_keypair,
    compute_shared_secret,
    derive_group_key,
    encrypt_x25519_private_key,
    decrypt_x25519_private_key,
    load_public_key_from_b64,
    X25519KeyPair,
)
from app.crypto.kdf import (
    derive_key_from_password,
    derive_key_deterministic,
    hash_password_for_storage,
    verify_password,
    needs_rehash,
    generate_salt,
    secure_compare,
    DerivedKey,
)

__all__ = [
    "generate_file_key",
    "generate_nonce",
    "encrypt",
    "decrypt",
    "decrypt_raw",
    "encrypt_string",
    "decrypt_string",
    "encrypt_key",
    "decrypt_key",
    "derive_key_from_bytes",
    "EncryptedData",
    "AES_KEY_SIZE",
    "AES_NONCE_SIZE",
    "generate_keypair",
    "encrypt_with_public_key",
    "decrypt_with_private_key",
    "encrypt_private_key",
    "decrypt_private_key",
    "sign_data",
    "verify_signature",
    "RSAKeyPair",
    "generate_x25519_keypair",
    "compute_shared_secret",
    "derive_group_key",
    "encrypt_x25519_private_key",
    "decrypt_x25519_private_key",
    "load_public_key_from_b64",
    "X25519KeyPair",
    "derive_key_from_password",
    "derive_key_deterministic",
    "hash_password_for_storage",
    "verify_password",
    "needs_rehash",
    "generate_salt",
    "secure_compare",
    "DerivedKey",
]
